import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem import rdDetermineBonds


# fmt: off
atom_symbols = {
    1: "H", 2: "He", 3: "Li", 4: "Be", 5: "B", 6: "C", 7: "N", 8: "O", 9: "F", 10: "Ne",
    11: "Na", 12: "Mg", 13: "Al", 14: "Si", 15: "P", 16: "S", 17: "Cl", 18: "Ar",
    19: "K", 20: "Ca", 21: "Sc", 22: "Ti", 23: "V", 24: "Cr", 25: "Mn", 26: "Fe",
    27: "Co", 28: "Ni", 29: "Cu", 30: "Zn"
}
# fmt: on


def create_xyz_block(symbols, coordinates):
    """
    Args:
        symbols (list): List of atomic symbols e.g., ['C', 'H', 'H', 'H', 'H']
        coordinates (np.array): N x 3 array of Cartesian coordinates

    Returns:
        str: A formatted XYZ block string
    """
    n_atoms = len(symbols)
    lines = [str(n_atoms), "Generated by Python"]

    for z, coord in zip(symbols, coordinates):
        label = atom_symbols.get(z)
        x, y, z = coord
        lines.append(f"{label:2s} {x:12.6f} {y:12.6f} {z:12.6f}")

    return "\n".join(lines)


# symbols = ['C', 'H', 'H', 'H', 'H']
# coords = np.array([
#     [ 0.0000,  0.0000,  0.0000],
#     [ 0.6291,  0.6291,  0.6291],
#     [-0.6291, -0.6291,  0.6291],
#     [ 0.6291, -0.6291, -0.6291],
#     [-0.6291,  0.6291, -0.6291]
# ])

# xyz_block = create_xyz_block(symbols, coords)
# mol = Chem.MolFromXYZBlock(xyz_block)


def xyz_to_graph(Z, coords, charge=0):

    mol = Chem.MolFromXYZBlock(create_xyz_block(Z, coords))
    mol = Chem.Mol(mol)
    # Chem.SanitizeMol(mol)
    Chem.SanitizeMol(
        mol,
        sanitizeOps=Chem.SanitizeFlags.SANITIZE_ALL
        ^ Chem.SanitizeFlags.SANITIZE_PROPERTIES,
    )
    rdDetermineBonds.DetermineConnectivity(mol)
    try:
        rdDetermineBonds.DetermineBondOrders(mol, charge)
    except ValueError:
        pass

    # rdDetermineBonds.DetermineBonds(mol, charge=charge)

    mol.UpdatePropertyCache()

    return mol


csv_path = "data/AQM-sample-2.csv"
df = pd.read_csv(csv_path)
df["atomic_numbers"] = df["atomic_numbers"].apply(eval)
df["gas_xyz"] = df["gas_xyz"].apply(eval)
# df["sol_xyz"] = df["sol_xyz"].apply(eval)
samples = df.to_dict(orient="records")
# solv_smiles = solv_smiles

for idx in range(len(samples)):
    print(f"Processing sample {idx+1}/{len(samples)}")
    row = samples[idx]
    Z = np.array(row["atomic_numbers"])
    gas_xyz = np.array(row["gas_xyz"]).reshape(-1, 3)
    sol_graph = xyz_to_graph(Z, gas_xyz)
